spring.application.name=management.task

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/tmanagement
#spring.datasource.username="Username
#spring.datasource.password= "password of sql data base"
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver